improve downstore to deal with sqfs and boot from USB stick

diff --git a/bin/yac_downstore b/bin/yac_downstore
--- a/bin/yac_downstore
+++ b/bin/yac_downstore
@@ -4,18 +4,43 @@
 
 function check_prerequisites {
 	local BOOT_PARTITION=$(mount | grep "on / type" | awk '{print $1}')
-	local DISKS=($(lsblk | grep disk | grep -v boot | awk '{print $1}'))
+	local DISKS=($(lsblk | grep disk | grep -v boot | sort | awk '{print $1}'))
 
 	INFO "list all partitions ..."
 	blkid | awk '{printf "\t%s\n", $0}'
 
 	for d in "${DISKS[@]}"; do
 		if [ "" != "$(echo ${BOOT_PARTITION} | grep $d)" ]; then
-			local BOOT_DISK=$d
-		else
-			export TARGET_DISK=$d
+			export BOOT_DISK=$d
+		fi
+		if [ "" != "$(echo $d | grep mmcblk)" ]; then
+			if [ "" != "$(parted /dev/$d print | grep '^Model:' | sed 's/^Model:\ //g' | grep '^MMC')" ]; then
+				export EMMC_DISK=$d
+			else
+				export SDXC_DISK=$d
+			fi
 		fi
 	done
+	INFO "BOOT_DISK = $(LIGHT_GREEN ${BOOT_DISK})"
+	INFO "EMMC_DISK = $(LIGHT_GREEN ${EMMC_DISK})"
+	INFO "SDXC_DISK = $(LIGHT_GREEN ${SDXC_DISK})"
+	[ "" == "${BOOT_DISK}" ] && ERR "missing BOOT_DISK from these disks" && lsblk | grep disk | grep -v boot | awk '{printf "\t%s\n", $1}' && return 1
+
+	if [ "${BOOT_DIRK}" != "${EMMC_DISK}" ] && [ "${BOOT_DISK}" != "${SDXC_DISK}" ]; then
+		INFO "detect current boot from USB stick: $(parted /dev/${BOOT_DISK} print | grep '^Model:' | sed 's/^Model:\ //g')"
+		INFO "using emmc disk as target: ${EMMC_DISK}"
+		export TARGET_DISK=${EMMC_DISK}
+	else
+		if [ "${BOOT_DISK}" == "${SDXC_DISK}" ]; then
+			INFO "detect current boot from micro SD card: $(parted /dev/${BOOT_DISK} print | grep '^Model:' | sed 's/^Model:\ //g')"
+			INFO "using emmc disk as target: ${EMMC_DISK}"
+			export TARGET_DISK=${EMMC_DISK}
+		else
+			INFO "detect current boot from eMMC: $(parted /dev/${BOOT_DISK} print | grep '^Model:' | sed 's/^Model:\ //g')"
+			INFO "restore is disallowed!!"
+			return 2
+		fi
+	fi
 
 	[ "" == "${BOOT_DISK}" ] && ERR "missing BOOT_DISK from these disks" && lsblk | grep disk | grep -v boot | awk '{printf "\t%s\n", $1}' && return 1
 	[ "" == "${TARGET_DISK}" ] && ERR "missing TARGET_DISK from these disks" && lsblk | grep disk | grep -v boot | awk '{printf "\t%s\n", $1}' && return 1
@@ -29,8 +54,8 @@ function check_prerequisites {
 	INFO "BOOT DISK: $(YELLOW ${BOOT_DISK}), size: $(LIGHT_GREEN ${BOOT_DISK_SIZE}), type: $(PURPLE ${BOOT_DISK_TYPE})"
 	INFO "TARGET DISK: $(YELLOW ${TARGET_DISK}), size: $(LIGHT_GREEN ${TARGET_DISK_SIZE}), type: $(PURPLE ${TARGET_DISK_TYPE})"
 
-	[ "" == "$(echo ${BOOT_DISK_TYPE} | grep '^SD')" ] && ERR "BOOT DISK is not SD card" && return 1
-	[ "" == "$(echo ${TARGET_DISK_TYPE} | grep '^MMC')" ] && ERR "TARGET DISK is not eMMC" && return 1
+	# [ "" == "$(echo ${BOOT_DISK_TYPE} | grep '^SD')" ] && ERR "BOOT DISK is not SD card" && return 1
+	# [ "" == "$(echo ${TARGET_DISK_TYPE} | grep '^MMC')" ] && ERR "TARGET DISK is not eMMC" && return 1
 }
 
 
@@ -38,28 +63,37 @@ function restore {
 	local SOURCE_DIR=$1
 	local DRIVE=/dev/${TARGET_DISK}
 	[ "" == "${MBR_SIZE}" ] && MBR_SIZE="1M"
-	[ "" == "${SOURCE_DIR}" ] && ERR "please specify the source directory with file contents and bootloader image to restore SD card" && return 1
+	[ "" == "${SOURCE_DIR}" ] && ERR "please specify the source directory with file contents and bootloader image to restore ${DRIVE}" && return 1
 	[ "" == "${DRIVE}" ] && ERR "please specify the target SD drive to restore, e.g. /dev/sdb" && return 1
 	[ "" == "$(which pv)" ] && ERR "please install pv" && return 1
 	[ "" == "$(which sfdisk)" ] && ERR "please install sfdisk" && return 1
 
 	[ ! -b "${DRIVE}" ] && ERR "invalid target drive: ${DRIVE}" && return 2
-	[ ! -f "${SOURCE_DIR}/bootloader.img" ] && ERR "invalid source directory (${SOURCE_DIR}): missing bootloader.img" && return 2
-	[ ! -f "${SOURCE_DIR}/partitions.sfdisk.dump" ] && ERR "invalid source directory (${SOURCE_DIR}): missing partitions.sfdisk.dump" && return 2
+	# [ ! -f "${SOURCE_DIR}/bootloader.img" ] && ERR "invalid source directory (${SOURCE_DIR}): missing bootloader.img" && return 2
+	# [ ! -f "${SOURCE_DIR}/partitions.sfdisk.dump" ] && ERR "invalid source directory (${SOURCE_DIR}): missing partitions.sfdisk.dump" && return 2
 	[ ! -d "${SOURCE_DIR}/p1" ] && ERR "invalid source directory (${SOURCE_DIR}): missing p1" && return 2
+	[ ! -d "${SOURCE_DIR}/p2" ] && ERR "invalid source directory (${SOURCE_DIR}): missing p2" && return 2
 
-	local UBOOT_SERVER="https://rcn-ee.com/repos/bootloader"
-	local UBOOT_BOARD="am335x_boneblack"
-	local UBOOT_BUILD_VERSION="v2018.01-r11"
-	local UBOOT_MLO="${UBOOT_SERVER}/${UBOOT_BOARD}/MLO-${UBOOT_BOARD}-${UBOOT_BUILD_VERSION}"
-	local UBOOT_IMG="${UBOOT_SERVER}/${UBOOT_BOARD}/u-boot-${UBOOT_BOARD}-${UBOOT_BUILD_VERSION}.img"
 	local UBOOT_MLO_FILE="/tmp/MLO"
 	local UBOOT_IMG_FILE="/tmp/u-boot.img"
-
-	wget -O ${UBOOT_MLO_FILE} ${UBOOT_MLO}
-	[ "0" != "$?" ] && ERR "failed to download $(basename ${UBOOT_MLO_FILE}) from ${UBOOT_MLO}" && return 3
-	wget -O ${UBOOT_IMG_FILE} ${UBOOT_IMG}
-	[ "0" != "$?" ] && ERR "failed to download $(basename ${UBOOT_IMG_FILE}) from ${UBOOT_IMG}" && return 3
+	if [ "true" == "${USE_ELINUX_UBOOT}" ]; then
+		local UBOOT_SERVER="https://rcn-ee.com/repos/bootloader"
+		local UBOOT_BOARD="am335x_boneblack"
+		local UBOOT_BUILD_VERSION="v2018.01-r11"
+		local UBOOT_MLO="${UBOOT_SERVER}/${UBOOT_BOARD}/MLO-${UBOOT_BOARD}-${UBOOT_BUILD_VERSION}"
+		local UBOOT_IMG="${UBOOT_SERVER}/${UBOOT_BOARD}/u-boot-${UBOOT_BOARD}-${UBOOT_BUILD_VERSION}.img"
+		wget -O ${UBOOT_MLO_FILE} ${UBOOT_MLO}
+		[ "0" != "$?" ] && ERR "failed to download $(basename ${UBOOT_MLO_FILE}) from ${UBOOT_MLO}" && return 3
+		wget -O ${UBOOT_IMG_FILE} ${UBOOT_IMG}
+		[ "0" != "$?" ] && ERR "failed to download $(basename ${UBOOT_IMG_FILE}) from ${UBOOT_IMG}" && return 3
+	else
+		local UBOOT_MLO_FILE_SRC="${SOURCE_DIR}/p1/opt/backup/uboot/$(basename ${UBOOT_MLO_FILE})"
+		local UBOOT_IMG_FILE_SRC="${SOURCE_DIR}/p1/opt/backup/uboot/$(basename ${UBOOT_IMG_FILE})"
+		[ ! -f "${UBOOT_MLO_FILE_SRC}" ] && ERR "missing ${UBOOT_MLO_FILE_SRC}" && return 3
+		[ ! -f "${UBOOT_IMG_FILE_SRC}" ] && ERR "missing ${UBOOT_IMG_FILE_SRC}" && return 3
+		cp -v ${UBOOT_MLO_FILE_SRC} ${UBOOT_MLO_FILE}
+		cp -v ${UBOOT_IMG_FILE_SRC} ${UBOOT_IMG_FILE}
+	fi
 
 	INFO "Umount all partitions for $(LIGHT_GREEN ${DRIVE})"
 	mount | grep ${DRIVE} | awk '{print $1}' | xargs -I{} sh -c "umount {}"
@@ -107,11 +141,6 @@ function restore {
 			INFO "missing ${SRC} to restore $(LIGHT_GREEN ${p})"
 		fi
 
-		#if [ "1" == "${NUM}" ]; then
-		#	RUN_CMD "mv ${DIR}/uEnv.txt ${DIR}/uEnv.txt.bak"
-		#	RUN_CMD "mv ${DIR}/uEnv-emmc.txt ${DIR}/uEnv.txt"
-		#fi
-
 		RUN_CMD umount ${p}
 		RUN_CMD sync
 	done
@@ -147,24 +176,40 @@ function download_latest_image_and_restore {
 		wget --user ${CLOUD_RELEASE_USER} --password ${CLOUD_RELEASE_PASS} -O ${ARCHIVE_FILE} ${URL}/${FILENAME}
 		[ "0" != "$?" ] && ERR "failed to down ${URL}/${FILENAME}" && exit 11
 	fi
-
+	[ "sqfs" == "${ARCHIVE_FILE#*.}" ] && local USE_SQFS="true" || local USE_SQFS="false"
 	local ARCHIVE_DIR="${YS_DAT_DIR}/tmp/${NAME}"
-	if [ "true" == "${SKIP_DECOMPRESSION_WHEN_EXIST}" ] && [ -d "${ARCHIVE_DIR}" ]; then
-		INFO "skip decompression because ${ARCHIVE_DIR} exists"
+
+	if [ "true" == "${USE_SQFS}" ]; then
+		RUN_CMD rm -rf ${ARCHIVE_DIR}
+		RUN_CMD mkdir -p ${ARCHIVE_DIR}
+		RUN_CMD mount ${ARCHIVE_FILE} ${ARCHIVE_DIR}
 	else
-		rm -rf ${ARCHIVE_DIR}
-		mkdir -p ${ARCHIVE_DIR}
-		INFO "decompressing ${ARCHIVE_FILE} to ${ARCHIVE_DIR} ..."
-		tar xf ${ARCHIVE_FILE} -C ${ARCHIVE_DIR}
-		[ "0" != "$?" ] && ERR "failed to decompress ${ARCHIVE}" && exit 12
+		if [ "true" == "${SKIP_DECOMPRESSION_WHEN_EXIST}" ] && [ -d "${ARCHIVE_DIR}" ]; then
+			INFO "skip decompression because ${ARCHIVE_DIR} exists"
+		else
+			rm -rf ${ARCHIVE_DIR}
+			mkdir -p ${ARCHIVE_DIR}
+			INFO "decompressing ${ARCHIVE_FILE} to ${ARCHIVE_DIR} ..."
+			tar xf ${ARCHIVE_FILE} -C ${ARCHIVE_DIR}
+			[ "0" != "$?" ] && ERR "failed to decompress ${ARCHIVE}" && exit 12
+		fi
 	fi
 
 	restore ${ARCHIVE_DIR}
 	INFO "done. (exit-code: $?)"
-	rm -rf ${ARCHIVE_DIR}
+
+	if [ "true" == "${USE_SQFS}" ]; then
+		RUN_CMD umount ${ARCHIVE_DIR}
+	else
+		if [ "true" == "${SKIP_DECOMPRESSION_WHEN_EXIST}" ]; then
+			INFO "nothing for cleanup"
+		else
+			RUN_CMD rm -rf ${ARCHIVE_DIR}
+		fi
+	fi
 }
 
 function yac_main {
-	check_prerequisites
+	check_prerequisites || exit $?
 	download_latest_image_and_restore $@
 }
