update registration script for production

diff --git a/bin/yac_register b/bin/yac_register
--- a/bin/yac_register
+++ b/bin/yac_register
@@ -58,6 +58,7 @@ function generate_yac_files_and_reboot {
 		echo ${TOKEN} > ${YAC_TOKEN_FILE}
 	fi
 
+	[ "true" == "${IGNORE_REBOOT}" ] && return 0
 	INFO "rebooting ..."
 	reboot
 }
@@ -65,27 +66,44 @@ function generate_yac_files_and_reboot {
 function register_production_node {
 	load_variables
 	[ "${BOARD_SERIAL_NUMBER}" != "${BOARD_UNIQUE_IDENTITY}" ] && [ "true" != "${FORCE}" ] && ERR "already register unique id $(LIGHT_GREEN ${BOARD_UNIQUE_IDENTITY}) (serial_number: $(YELLOW ${BOARD_SERIAL_NUMBER})), then skip registration." && exit 1
-	[ "" == "$(which avahi-browse)" ] && ERR "please install avahi-utils first" && exit 1
+	[ "" == "${PORT}" ] && local PORT=7070  # default tic-dm-proxy port number
+	[ "" == "${VERSION}" ] && local VERSION=${BOARD_BASE_VERSION}
+	if [ "" == "${IP}" ]; then
+		[ "" == "$(which avahi-browse)" ] && ERR "please install avahi-utils first" && exit 1
+		INFO "looking for tic-dm-proxy server running at port ${PORT} in local network ..."
+		local IP=$(avahi-browse -d local _http._tcp -t -r -p | grep ";${PORT};$" | awk -F';' '{print $8}' | head -n1)
+		local EXIT_CODE=$?
+		[ "0" != "${EXIT_CODE}" ] && ERR "failed to lookup tic-dm-proxy server, err: ${EXIT_CODE}" && exit ${EXIT_CODE}
+		[ "" == "${IP}" ] && ERR "missing tic-dm-proxy server at local network" && exit 1
+	fi
 
-	local PORT="7070"
-	INFO "looking for tic-dm-proxy server running at port ${PORT} in local network ..."
-	local IP=$(avahi-browse -d local _http._tcp -t -r -p | grep ";${PORT};$" | awk -F';' '{print $8}' | head -n1)
-	local EXIT_CODE=$?
-	[ "0" != "${EXIT_CODE}" ] && ERR "failed to lookup tic-dm-proxy server, err: ${EXIT_CODE}" && exit ${EXIT_CODE}
-	[ "" == "${IP}" ] && ERR "missing tic-dm-proxy server at local network" && exit 1
+	if [ "00:00:00:00:00:00" == "${MACADDR_BLEMO}" ] && [ "true" != "${IGNORE_BLEMO}" ]; then
+		while true; do
+			export MACADDR_BLEMO=$(yac_hook get_macaddr blemo)
+			if [ "" == "${MACADDR_BLEMO}" ]; then
+				INFO "waiting for BLEMO mac address ..."
+				sleep 1
+			else
+				INFO "got blemo mac address: ${MACADDR_BLEMO}"
+				break
+			fi
+		done
+	fi
 
 	local TMP=$(mktemp /tmp/XXXXXX)
-	INFO "posting data to http://${IP}:${PORT}/api/v3/nodes/${BOARD_PROFILE}/create-production-node/${BOARD_SERIAL_NUMBER} ..."
+	INFO "posting data to http://${IP}:${PORT}/api/v3/nodes/${BOARD_PROFILE}/update-production-node/${BOARD_SERIAL_NUMBER} ..."
 
 	http \
 		--check-status \
 		--ignore-stdin \
-		http://${IP}:${PORT}/api/v3/nodes/${BOARD_PROFILE}/create-production-node/${BOARD_SERIAL_NUMBER} \
+		http://${IP}:${PORT}/api/v3/nodes/${BOARD_PROFILE}/update-production-node/${BOARD_SERIAL_NUMBER} \
 			device=$(echo ${BOARD} | tr [a-z] [A-Z]) \
-			version=${BOARD_BASE_VERSION} \
+			version=${VERSION} \
 			macaddr_eth=${MACADDR_ETH} \
 			macaddr_usb=${MACADDR_USB} \
 			macaddr_wlan=${MACADDR_WLAN} \
+			macaddr_ble=${MACADDR_BLE} \
+			macaddr_blemo=${MACADDR_BLEMO} \
 			> ${TMP}
 	local EXIT_CODE=$?
 	[ "0" != "${EXIT_CODE}" ] && ERR "failed to register" && cat ${TMP} && rm -f ${TMP} && exit 1
