update downstore script to use 1st cmdline argument as archive image to restore eMMC

diff --git a/bin/yac_downstore b/bin/yac_downstore
--- a/bin/yac_downstore
+++ b/bin/yac_downstore
@@ -17,8 +17,8 @@ function check_prerequisites {
 		fi
 	done
 
-	[ "" == "${BOOT_DISK}" ] && ERR "missing BOOT_DISK from these disks" && lsblk | grep disk | grep -v boot | awk '{printf "\t%s\n", $1}' && exit 1
-	[ "" == "${TARGET_DISK}" ] && ERR "missing TARGET_DISK from these disks" && lsblk | grep disk | grep -v boot | awk '{printf "\t%s\n", $1}' && exit 1
+	[ "" == "${BOOT_DISK}" ] && ERR "missing BOOT_DISK from these disks" && lsblk | grep disk | grep -v boot | awk '{printf "\t%s\n", $1}' && return 1
+	[ "" == "${TARGET_DISK}" ] && ERR "missing TARGET_DISK from these disks" && lsblk | grep disk | grep -v boot | awk '{printf "\t%s\n", $1}' && return 1
 
 	local BOOT_DISK_SIZE=$(lsblk | grep "^${BOOT_DISK} " | awk '{print $4}')
 	local BOOT_DISK_TYPE=$(parted /dev/${BOOT_DISK} print | grep "^Model:" | sed 's/^Model:\ //g')
@@ -29,8 +29,8 @@ function check_prerequisites {
 	INFO "BOOT DISK: $(YELLOW ${BOOT_DISK}), size: $(LIGHT_GREEN ${BOOT_DISK_SIZE}), type: $(PURPLE ${BOOT_DISK_TYPE})"
 	INFO "TARGET DISK: $(YELLOW ${TARGET_DISK}), size: $(LIGHT_GREEN ${TARGET_DISK_SIZE}), type: $(PURPLE ${TARGET_DISK_TYPE})"
 
-	[ "" == "$(echo ${BOOT_DISK_TYPE} | grep '^SD')" ] && ERR "BOOT DISK is not SD card" && exit 1
-	[ "" == "$(echo ${TARGET_DISK_TYPE} | grep '^MMC')" ] && ERR "TARGET DISK is not eMMC" && exit 1
+	[ "" == "$(echo ${BOOT_DISK_TYPE} | grep '^SD')" ] && ERR "BOOT DISK is not SD card" && return 1
+	[ "" == "$(echo ${TARGET_DISK_TYPE} | grep '^MMC')" ] && ERR "TARGET DISK is not eMMC" && return 1
 }
 
 
@@ -38,16 +38,15 @@ function restore {
 	local SOURCE_DIR=$1
 	local DRIVE=/dev/${TARGET_DISK}
 	[ "" == "${MBR_SIZE}" ] && MBR_SIZE="1M"
-	[ "" == "${SOURCE_DIR}" ] && ERR "please specify the source directory with file contents and bootloader image to restore SD card" && exit 1
-	[ "" == "${DRIVE}" ] && ERR "please specify the target SD drive to restore, e.g. /dev/sdb" && exit 1
-	[ "" == "$(which pv)" ] && ERR "please install pv" && exit 1
-	[ "" == "$(which sfdisk)" ] && ERR "please install sfdisk" && exit 1
-	check_prerequisites pv sfdisk
+	[ "" == "${SOURCE_DIR}" ] && ERR "please specify the source directory with file contents and bootloader image to restore SD card" && return 1
+	[ "" == "${DRIVE}" ] && ERR "please specify the target SD drive to restore, e.g. /dev/sdb" && return 1
+	[ "" == "$(which pv)" ] && ERR "please install pv" && return 1
+	[ "" == "$(which sfdisk)" ] && ERR "please install sfdisk" && return 1
 
-	[ ! -b "${DRIVE}" ] && ERR "invalid target drive: ${DRIVE}" && exit 1
-	[ ! -f "${SOURCE_DIR}/bootloader.img" ] && ERR "invalid source directory (${SOURCE_DIR}): missing bootloader.img" && exit 1 
-	[ ! -f "${SOURCE_DIR}/partitions.sfdisk.dump" ] && ERR "invalid source directory (${SOURCE_DIR}): missing partitions.sfdisk.dump" && exit 1 
-	[ ! -d "${SOURCE_DIR}/p1" ] && ERR "invalid source directory (${SOURCE_DIR}): missing p1" && exit 1 
+	[ ! -b "${DRIVE}" ] && ERR "invalid target drive: ${DRIVE}" && return 2
+	[ ! -f "${SOURCE_DIR}/bootloader.img" ] && ERR "invalid source directory (${SOURCE_DIR}): missing bootloader.img" && return 2
+	[ ! -f "${SOURCE_DIR}/partitions.sfdisk.dump" ] && ERR "invalid source directory (${SOURCE_DIR}): missing partitions.sfdisk.dump" && return 2
+	[ ! -d "${SOURCE_DIR}/p1" ] && ERR "invalid source directory (${SOURCE_DIR}): missing p1" && return 2
 
 	local UBOOT_SERVER="https://rcn-ee.com/repos/bootloader"
 	local UBOOT_BOARD="am335x_boneblack"
@@ -58,9 +57,9 @@ function restore {
 	local UBOOT_IMG_FILE="/tmp/u-boot.img"
 
 	wget -O ${UBOOT_MLO_FILE} ${UBOOT_MLO}
-	[ "0" != "$?" ] && ERR "failed to download $(basename ${UBOOT_MLO_FILE}) from ${UBOOT_MLO}" && exit 1
+	[ "0" != "$?" ] && ERR "failed to download $(basename ${UBOOT_MLO_FILE}) from ${UBOOT_MLO}" && return 3
 	wget -O ${UBOOT_IMG_FILE} ${UBOOT_IMG}
-	[ "0" != "$?" ] && ERR "failed to download $(basename ${UBOOT_IMG_FILE}) from ${UBOOT_IMG}" && exit 1
+	[ "0" != "$?" ] && ERR "failed to download $(basename ${UBOOT_IMG_FILE}) from ${UBOOT_IMG}" && return 3
 
 	INFO "Umount all partitions for $(LIGHT_GREEN ${DRIVE})"
 	mount | grep ${DRIVE} | awk '{print $1}' | xargs -I{} sh -c "umount {}"
@@ -70,9 +69,6 @@ function restore {
 	RUN_CMD dd if=/dev/zero of=${DRIVE} bs=${MBR_SIZE} count=1
 	RUN_CMD sync
 
-	#INFO "Copy MBR (MLO and U-Boot) to SD card"
-	#RUN_CMD dd if=${SOURCE_DIR}/bootloader.img of=${DRIVE}
-	#RUN_CMD sync
 	INFO "Copy MBR (MLO and U-Boot) to SD card: version: $(LIGHT_GREEN ${UBOOT_BUILD_VERSION})"
 	RUN_CMD dd if=${UBOOT_MLO_FILE} of=${DRIVE} count=1 seek=1 conv=notrunc bs=128k
 	RUN_CMD dd if=${UBOOT_IMG_FILE} of=${DRIVE} count=2 seek=1 conv=notrunc bs=384k
@@ -96,9 +92,9 @@ function restore {
 		local DIR="/mnt/${NAME}"
 		local SRC="${SOURCE_DIR}/p${NUM}"
 
-		RUN_CMD mkfs.ext4 ${p} || exit 1
+		RUN_CMD mkfs.ext4 ${p} || return 4
 		RUN_CMD mkdir -p ${DIR}
-		RUN_CMD mount ${p} ${DIR} || exit 1
+		RUN_CMD mount ${p} ${DIR} || return 4
 
 		if [ -d "${SRC}" ]; then
 			cd ${SRC}
@@ -111,41 +107,48 @@ function restore {
 			INFO "missing ${SRC} to restore $(LIGHT_GREEN ${p})"
 		fi
 
-		if [ "1" == "${NUM}" ]; then
-			RUN_CMD "mv ${DIR}/uEnv.txt ${DIR}/uEnv.txt.bak"
-			RUN_CMD "mv ${DIR}/uEnv-emmc.txt ${DIR}/uEnv.txt"
-		fi
+		#if [ "1" == "${NUM}" ]; then
+		#	RUN_CMD "mv ${DIR}/uEnv.txt ${DIR}/uEnv.txt.bak"
+		#	RUN_CMD "mv ${DIR}/uEnv-emmc.txt ${DIR}/uEnv.txt"
+		#fi
 
 		RUN_CMD umount ${p}
 		RUN_CMD sync
 	done
-
-	INFO "done."
 }
 
 
 function download_latest_image_and_restore {
-	[ "99991231z" == "${BOARD_BASE_VERSION}" ] && ERR "current BOARD_BASE_VERSION is 99991231z, which is invalid" && exit 2
-	local TMP_FILE=$(mktemp /tmp/XXXXXX)
-	local URL="${CLOUD_RELEASE_URL}/projects/${BOARD_PROFILE}/nodes/${BOARD}-sd-base/"
-	INFO "looking current base version ${BOARD_BASE_VERSION} from ${URL} ..."
-	http -a ${CLOUD_RELEASE_USER}:${CLOUD_RELEASE_PASS} ${URL} > ${TMP_FILE}
-	[ "0" != "$?" ] && ERR "failed to get file list from ${SERVER}/projects/foop/nodes/bbg-sd-base/" && rm -f ${TMP_FILE} && exit 2
-	local FILENAME=$(cat ${TMP_FILE} | jq ".[] | .name" | sed 's/\"//g' | grep "${BOARD_BASE_VERSION}.tar")
-	rm -f TMP_FILE
-	[ "" == "${FILENAME}" ] && ERR "no such base version: ${BOARD_BASE_VERSION}" && exit 2
-	INFO "Found. $(LIGHT_GREEN ${FILENAME})"
+	local LOCAL_ARCHIVE=$1
+	INFO "LOCAL_ARCHIVE = ${LOCAL_ARCHIVE}"
+	if [ "" == "${LOCAL_ARCHIVE}" ]; then
+		[ "99991231z" == "${BOARD_BASE_VERSION}" ] && ERR "current BOARD_BASE_VERSION is 99991231z, which is invalid" && exit 10
+		local TMP_FILE=$(mktemp /tmp/XXXXXX)
+		local URL="${CLOUD_RELEASE_URL}/projects/${BOARD_PROFILE}/nodes/${BOARD}-sd-base/"
+		INFO "looking current base version ${BOARD_BASE_VERSION} from ${URL} ..."
+		http -a ${CLOUD_RELEASE_USER}:${CLOUD_RELEASE_PASS} ${URL} > ${TMP_FILE}
+		[ "0" != "$?" ] && ERR "failed to get file list from ${SERVER}/projects/foop/nodes/bbg-sd-base/" && rm -f ${TMP_FILE} && exit 10
+		local FILENAME=$(cat ${TMP_FILE} | jq ".[] | .name" | sed 's/\"//g' | grep "${BOARD_BASE_VERSION}.tar")
+		rm -f TMP_FILE
+		[ "" == "${FILENAME}" ] && ERR "no such base version: ${BOARD_BASE_VERSION}" && exit 10
+		INFO "Found. $(LIGHT_GREEN ${FILENAME}) from ${CLOUD_RELEASE_URL}"
+		local NAME=${FILENAME%%.*}
+		local ARCHIVE_FILE="/tmp/${FILENAME}"
+	else
+		[ ! -f "${LOCAL_ARCHIVE}" ] && ERR "no such local archive file: ${LOCAL_ARCHIVE}" && exit 10
+		local FILENAME=$(basename ${LOCAL_ARCHIVE})
+		local NAME=${FILENAME%%.*}
+		local ARCHIVE_FILE=${LOCAL_ARCHIVE}
+	fi
 
-	local NAME=${FILENAME%%.*}
-	local ARCHIVE_DIR="/tmp/${NAME}"
-	local ARCHIVE_FILE="/tmp/${FILENAME}"
 	if [ -f ${ARCHIVE_FILE} ]; then
 		INFO "reuse the existed archive file: ${ARCHIVE_FILE} ($(YELLOW $(ls -alh ${ARCHIVE_FILE} | awk '{print $5}')))"
 	else
 		wget --user ${CLOUD_RELEASE_USER} --password ${CLOUD_RELEASE_PASS} -O ${ARCHIVE_FILE} ${URL}/${FILENAME}
-		[ "0" != "$?" ] && ERR "failed to down ${URL}/${FILENAME}" && exit 2
+		[ "0" != "$?" ] && ERR "failed to down ${URL}/${FILENAME}" && exit 11
 	fi
 
+	local ARCHIVE_DIR="${YS_DAT_DIR}/tmp/${NAME}"
 	if [ "true" == "${SKIP_DECOMPRESSION_WHEN_EXIST}" ] && [ -d "${ARCHIVE_DIR}" ]; then
 		INFO "skip decompression because ${ARCHIVE_DIR} exists"
 	else
@@ -153,13 +156,15 @@ function download_latest_image_and_restore {
 		mkdir -p ${ARCHIVE_DIR}
 		INFO "decompressing ${ARCHIVE_FILE} to ${ARCHIVE_DIR} ..."
 		tar xf ${ARCHIVE_FILE} -C ${ARCHIVE_DIR}
-		[ "0" != "$?" ] && ERR "failed to decompress ${ARCHIVE}" && exit 2
+		[ "0" != "$?" ] && ERR "failed to decompress ${ARCHIVE}" && exit 12
 	fi
 
 	restore ${ARCHIVE_DIR}
+	INFO "done. (exit-code: $?)"
+	rm -rf ${ARCHIVE_DIR}
 }
 
 function yac_main {
 	check_prerequisites
-	download_latest_image_and_restore
+	download_latest_image_and_restore $@
 }
